language: rust
rust:
  - stable
addons:
  apt:
    packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-dev
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
  - curl -kLO https://slepin.fr/obs-ndi/ci/ndisdk-slim-v3.5-linux.zip -f --retry 5 && unzip ./ndisdk-slim-v3.5-linux.zip
script:
  - cargo fmt -- --check
  - touch ./src/*.rs && cargo clippy -- -D warnings
  - cargo build