[package]
name = "gst-plugin-ndi"
version = "1.0.0"
authors = ["Ruben Gonzalez <rubenrua@teltek.es>", "Daniel Vilar <daniel.peiteado@teltek.es>"]
repository = "https://github.com/teltek/gst-plugin-ndi"
license = "LGPL"

[dependencies]
gobject-subclass = "0.2"
gst-plugin = "0.3"
glib = "0.6"
gstreamer = "0.12"
gstreamer-base = "0.12"
gstreamer-video = "0.12"
gstreamer-audio = "0.12"
lazy_static = "1.1.0"

[lib]
name = "gstndi"
crate-type = ["cdylib"]
path = "src/lib.rs"
